[[main]]
  name = "主页"
  url = ""
  weight = -110

[[main]]
  name = "技术相关"
  url = "/post/technologys/"
  weight = -109

[[main]]
  name = "伤寒杂论"
  url = "/post/rescues/"
  weight = -108

[[main]]
  name = "旅行记录"
  url = "/post/travels/"
  weight = -107

[[main]]
  name = "家庭生活"
  url = "/post/lifes/"
  weight = -106

# Submenus are done this way: parent -> identifier

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/volume-ji"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"